import { LevelDef } from '../core/level';

/**
 * Level maps are ASCII art — see src/core/level.ts for the legend.
 * Design intent (docs/team/06 §6): each level teaches exactly one idea.
 * Boards are 16 wide since the 2026-08 map-size upgrade; the renderer
 * auto-fits any size, so feel free to go bigger in the editor.
 */
export const LEVELS: LevelDef[] = [
  {
    name: '1 · Warm Up',
    hint: 'Arrows/WASD to move. Reach the door.',
    map: `
................
................
................
....######......
................
................
................
.21H........E...
################
`,
  },
  {
    name: '2 · Snack Time',
    hint: 'Doors only open when every apple is eaten. Eating makes you longer.',
    map: `
................
................
................
................
................
.........o......
.......o###.....
.1H.o.......E...
################
`,
  },
  {
    name: '3 · The Gap',
    hint: 'A longer body bridges wider gaps. Do not fall!',
    map: `
................
................
................
................
................
................
................
.1Hoo....o..E...
#####...##.#####
`,
  },
  {
    name: '4 · Nail Bed',
    hint: 'Spikes kill on impact — but hanging above them is fine.',
    map: `
................
................
................
................
................
................
.21Hoo..oo....E.
#####^^^##^^^^##
################
`,
  },
  {
    name: '5 · Lock & Key',
    hint: 'Grab the key, then open the lock box with it.',
    map: `
................
................
......k.........
.....###........
................
.21H.o......L.E.
################
`,
  },
  {
    name: '6 · Shed Lab (draft)',
    hint: 'X drops a crate where your tail is — even in MID-AIR. Experiment!',
    map: `
................
................
..21H...........
########..######
................
........o..o....
................
################
`,
  },
];
