import { LevelDef } from '../core/level';

/**
 * Campaign levels — every map is verified by the BFS solver in
 * tests/levels.test.ts (solvable, with measured minimum move counts),
 * and the finale is verified to REQUIRE the shed mechanic.
 *
 * Design follows the Snakebird playbook: the direct path is a trap, fruit
 * order is forced by terrain, growth changes what is possible, and drops
 * are one-way commitments. Min-move counts: 17/19/18/21/20/23.
 */
export const LEVELS: LevelDef[] = [
  {
    name: '1 · First Steps',
    hint: 'The shortest path is a lie.',
    map: `
............
............
............
............
..o.........
..#.....E...
..#..o.###..
21H....#....
###########.
`,
  },
  {
    name: '2 · Spiral Down',
    hint: 'Round and round, then back again.',
    map: `
............
.21H..o.....
.#####.##...
........#...
..o.....#...
.###....#...
........#...
...E....#...
..####..#...
............
`,
  },
  {
    name: '3 · Nail Garden',
    hint: 'Teeth below — cross where your body can reach.',
    map: `
..............
..............
..............
..............
..o.....o.....
..#.....#.....
21H..........E
#####^^##SS###
`,
  },
  {
    name: '4 · Keyring',
    hint: 'One key opens one lock. Spend wisely.',
    map: `
..............
..............
..k...........
..##......D...
..........##..
.21H.L.o......
.#####.###.#..
.......#k..#..
.......####...
`,
  },
  {
    name: '5 · The Vault',
    hint: 'Catch the key on your way down.',
    map: `
............
.21H..o.....
.#####.##...
........#...
..o...k.#...
.###....#...
...##...#...
..#E.L..#...
..######....
............
`,
  },
  {
    name: '6 · The Pocket',
    hint: 'No way back up… unless you leave something behind.',
    map: `
............
.21H........
.####...#...
.E..#...#...
.####.o.#...
....#...#...
....#o.o#...
....#...#...
....######..
............
`,
  },
];
